# Generated by Django 5.1.6 on 2025-02-23 17:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Teklif Fiyatı')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Bitiş Tarihi')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('accepted', 'Kabul Edildi'), ('rejected', 'Reddedildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('cargo_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='Profile.cargoowner', verbose_name='Yük Sahibi')),
                ('cargo_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='cargo.cargopost', verbose_name='Yük İlanı')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_offers', to='Profile.transporter', verbose_name='Taşıyıcı')),
            ],
            options={
                'verbose_name': 'Teklif',
                'verbose_name_plural': 'Teklifler',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='offer_offer_status_95ef93_idx'), models.Index(fields=['cargo_owner'], name='offer_offer_cargo_o_d6970e_idx'), models.Index(fields=['transporter'], name='offer_offer_transpo_19c8f5_idx')],
            },
        ),
    ]
