# Generated by Django 5.1.6 on 2025-03-02 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_user_options_alter_cargoowner_address_and_more'),
        ('cargo', '0002_cargopost_package_count_alter_cargopost_cargo_type_and_more'),
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='start_date',
        ),
        migrations.AddField(
            model_name='offer',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Teslim Tarihi'),
        ),
        migrations.AddField(
            model_name='offer',
            name='pickup_date',
            field=models.DateField(blank=True, null=True, verbose_name='Yükleme Tarihi'),
        ),
        migrations.AddField(
            model_name='offer',
            name='response_note',
            field=models.TextField(blank=True, help_text='Yük sahibinin teklife verdiği yanıt notu', null=True, verbose_name='Yanıt Notu'),
        ),
        migrations.AddField(
            model_name='offer',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='Bu tarihten sonra teklif otomatik olarak süresi dolmuş olarak işaretlenir', null=True, verbose_name='Geçerlilik Süresi'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='cargo_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_received', to='Profile.cargoowner', verbose_name='Yük Sahibi'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('accepted', 'Kabul Edildi'), ('rejected', 'Reddedildi'), ('cancelled', 'İptal Edildi'), ('expired', 'Süresi Doldu')], default='pending', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='transporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_sent', to='Profile.transporter', verbose_name='Taşıyıcı'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['created_at'], name='offer_offer_created_a61734_idx'),
        ),
    ]
