# Generated by Django 5.1.6 on 2025-03-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_remove_offer_end_date_remove_offer_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('accepted', 'Kabul Edildi'), ('rejected', 'Reddedildi'), ('cancelled', 'İptal Edildi'), ('expired', 'Süresi Doldu'), ('withdrawn', 'Geri Çekildi')], default='pending', max_length=20, verbose_name='Durum'),
        ),
    ]
