# Generated by Django 5.1.6 on 2025-03-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_alter_offer_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='offer',
            name='offer_offer_status_95ef93_idx',
        ),
        migrations.RemoveIndex(
            model_name='offer',
            name='offer_offer_cargo_o_d6970e_idx',
        ),
        migrations.RemoveIndex(
            model_name='offer',
            name='offer_offer_transpo_19c8f5_idx',
        ),
        migrations.RemoveIndex(
            model_name='offer',
            name='offer_offer_created_a61734_idx',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='note',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='pickup_date',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='response_note',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='offer',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Geçerlilik Süresi'),
        ),
        migrations.AddField(
            model_name='offer',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Mesaj'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Teklif Fiyatı (TL)'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('accepted', 'Kabul Edildi'), ('rejected', 'Reddedildi'), ('cancelled', 'İptal Edildi'), ('expired', 'Süresi Doldu'), ('withdrawn', 'Geri Çekildi')], default='pending', max_length=10, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
    ]
