# Generated by Django 5.1.6 on 2025-04-02 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0005_cargopost_delivery_latitude_and_more'),
        ('offer', '0005_offer_response_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='cargo_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='cargo.cargopost', verbose_name='Yük İlanı'),
        ),
    ]
