# Generated by Django 5.1.6 on 2025-02-23 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.TextField(verbose_name='Güzergah')),
                ('start_date', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateTimeField(verbose_name='Bitiş Tarihi')),
                ('vehicle_type', models.CharField(choices=[('truck', 'Kamyon'), ('semi_truck', 'Tır'), ('pickup', 'Kamyonet'), ('van', 'Van')], max_length=20, verbose_name='Araç Tipi')),
                ('vehicle_capacity', models.IntegerField(verbose_name='Araç Kapasitesi (kg)')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='active', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportations', to='Profile.transporter', verbose_name='Taşıyıcı')),
            ],
            options={
                'verbose_name': 'Taşıma',
                'verbose_name_plural': 'Taşımalar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='transportat_status_c506c9_idx'), models.Index(fields=['transporter'], name='transportat_transpo_e476f8_idx')],
            },
        ),
    ]
