# Generated by Django 5.1.6 on 2025-03-07 21:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_alter_transporter_vehicle_type'),
        ('cargo', '0003_remove_cargopost_cargo_cargo_created_0e9fb8_idx_and_more'),
        ('offer', '0005_offer_response_note'),
        ('transportation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportationRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_cargo_owner', models.BooleanField(default=True, verbose_name='Yük Sahibinden')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Değerlendirme (1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='Yorum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Değerlendirme Tarihi')),
            ],
            options={
                'verbose_name': 'Taşıma Değerlendirme',
                'verbose_name_plural': 'Taşıma Değerlendirmeleri',
            },
        ),
        migrations.CreateModel(
            name='TransportationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Not')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Enlem')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Boylam')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Taşıma Güncelleme',
                'verbose_name_plural': 'Taşıma Güncellemeleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='transportation',
            name='transportat_status_c506c9_idx',
        ),
        migrations.RemoveIndex(
            model_name='transportation',
            name='transportat_transpo_e476f8_idx',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='route',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='vehicle_capacity',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='transportation',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='İptal Nedeni'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='İptal Tarihi'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('cargo_owner', 'Yük Sahibi'), ('transporter', 'Taşıyıcı'), ('admin', 'Admin')], max_length=20, null=True, verbose_name='İptal Eden'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='cargo_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transportations', to='Profile.cargoowner', verbose_name='Yük Sahibi'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='cargo_post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transportation', to='cargo.cargopost', verbose_name='İlgili İlan'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Güncel Enlem'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Güncel Boylam'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='delivery_confirmed',
            field=models.BooleanField(default=False, verbose_name='Teslimat Onayı'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='delivery_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Teslimat Onay Tarihi'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='delivery_requested',
            field=models.BooleanField(default=False, verbose_name='Teslimat Talebi'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='delivery_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Teslimat Talep Tarihi'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='estimated_arrival',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tahmini Varış'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Konum Güncellemesi'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='offer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transportation', to='offer.offer', verbose_name='Kabul Edilen Teklif'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='pickup_confirmed',
            field=models.BooleanField(default=False, verbose_name='Yükleme Onayı'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='pickup_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yükleme Onay Tarihi'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='pickup_requested',
            field=models.BooleanField(default=False, verbose_name='Yükleme Talebi'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='pickup_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yükleme Talep Tarihi'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='status',
            field=models.CharField(choices=[('awaiting_pickup', 'Yükleme Bekliyor'), ('in_transit', 'Taşınıyor'), ('delivered', 'Teslim Edildi'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='awaiting_pickup', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='transporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transportations', to='Profile.transporter', verbose_name='Taşıyıcı'),
        ),
        migrations.AddField(
            model_name='transportationrating',
            name='transportation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='transportation.transportation', verbose_name='Taşıma'),
        ),
        migrations.AddField(
            model_name='transportationupdate',
            name='transportation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='transportation.transportation', verbose_name='Taşıma'),
        ),
        migrations.AddField(
            model_name='transportationupdate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterUniqueTogether(
            name='transportationrating',
            unique_together={('transportation', 'from_cargo_owner')},
        ),
    ]
