# Generated by Django 5.1.6 on 2025-03-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0002_transportationrating_transportationupdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Teslimat Adresi'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Teslimat Şehri'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='delivery_country',
            field=models.CharField(blank=True, default='Türkiye', max_length=100, verbose_name='Teslimat Ülkesi'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tahmini Teslimat Tarihi'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='estimated_pickup_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tahmini Yükleme Tarihi'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yükleme Adresi'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='pickup_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Yükleme Şehri'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='pickup_country',
            field=models.CharField(blank=True, default='Türkiye', max_length=100, verbose_name='Yükleme Ülkesi'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taşıma Ücreti'),
        ),
    ]
