# Generated by Django 5.1.6 on 2025-03-31 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0003_transportation_delivery_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSocketToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websocket_tokens', to='transportation.transportation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websocket_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WebSocket Token',
                'verbose_name_plural': 'WebSocket Tokens',
                'indexes': [models.Index(fields=['user', 'transportation', 'is_used'], name='transportat_user_id_f859b1_idx'), models.Index(fields=['token', 'is_used'], name='transportat_token_33e365_idx')],
            },
        ),
    ]
