# Generated by Django 5.1.6 on 2025-04-02 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0005_cargopost_delivery_latitude_and_more'),
        ('transportation', '0004_websockettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='cargo_post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportation', to='cargo.cargopost', verbose_name='İlgili İlan'),
        ),
    ]
