# Generated by Django 5.1.6 on 2025-04-11 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0005_alter_transportation_cargo_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Enlem')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Boylam')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Not')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zaman')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='transportation.transportation', verbose_name='Taşıma')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Konum Geçmişi',
                'verbose_name_plural': 'Konum Geçmişleri',
                'ordering': ['-timestamp'],
            },
        ),
    ]
