# Generated by Django 5.1.6 on 2025-04-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0006_locationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='cargo_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transportation',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
