# Generated by Django 5.1.6 on 2025-04-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0007_transportation_cargo_type_transportation_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Teslimat Noktası Enlemi'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Teslimat Noktası Boylamı'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Yükleme Noktası Enlemi'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Yükleme Noktası Boylamı'),
        ),
    ]
