# Generated by Django 5.1.6 on 2025-02-23 20:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Kullanıcı', 'verbose_name_plural': 'Kullanıcılar'},
        ),
        migrations.AlterField(
            model_name='cargoowner',
            name='address',
            field=models.TextField(verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='cargoowner',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Firma Adı'),
        ),
        migrations.AlterField(
            model_name='cargoowner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='cargoowner',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Telefon numarası '+999999999' formatında olmalıdır.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='cargoowner',
            name='tax_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Vergi Numarası'),
        ),
        migrations.AlterField(
            model_name='cargoowner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='cargoowner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_owner', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='address',
            field=models.TextField(verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Telefon numarası '+999999999' formatında olmalıdır.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='tax_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Vergi Numarası'),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transporter', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Firma Adı'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Telefon numarası '+999999999' formatında olmalıdır.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tax_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Vergi Numarası'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('cargo_owner', 'Yük Sahibi'), ('transporter', 'Taşıyıcı')], max_length=20, null=True, verbose_name='Kullanıcı Tipi'),
        ),
    ]
