# Generated by Django 5.1.6 on 2025-03-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_user_options_alter_cargoowner_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporter',
            name='vehicle_type',
            field=models.CharField(choices=[('truck', 'Kamyon'), ('small_truck', 'Küçük Kamyon'), ('medium_truck', 'Orta Boy Kamyon'), ('large_truck', 'Büyük Kamyon'), ('semi_truck', 'Tır'), ('refrigerated_truck', 'Frigorifik Araç'), ('flatbed_truck', 'Açık Kasa'), ('tanker', 'Tanker'), ('container_truck', 'Konteyner Taşıyıcı'), ('car_carrier', 'Oto Taşıyıcı'), ('pickup', 'Kamyonet'), ('van', 'Van'), ('other', 'Diğer')], max_length=20, verbose_name='Araç Tipi'),
        ),
    ]
