# Generated by Django 5.1.6 on 2025-02-23 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='İlan Başlığı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('pending', 'Beklemede'), ('in_transit', 'Taşınıyor'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='active', max_length=20, verbose_name='Durum')),
                ('pickup_location', models.CharField(max_length=200, verbose_name='Alış Noktası')),
                ('delivery_location', models.CharField(max_length=200, verbose_name='Teslim Noktası')),
                ('cargo_type', models.CharField(choices=[('parcel', 'Koli'), ('pallet', 'Palet'), ('bulk', 'Dökme Yük'), ('vehicle', 'Araç'), ('container', 'Konteyner')], max_length=20, verbose_name='Yük Tipi')),
                ('required_vehicle', models.CharField(choices=[('truck', 'Kamyon'), ('semi_truck', 'Tır'), ('pickup', 'Kamyonet'), ('van', 'Van')], max_length=20, verbose_name='Gerekli Araç Tipi')),
                ('weight', models.FloatField(verbose_name='Ağırlık (kg)')),
                ('volume', models.FloatField(blank=True, null=True, verbose_name='Hacim (m³)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Teklif Edilen Fiyat')),
                ('pickup_date', models.DateField(verbose_name='Alış Tarihi')),
                ('delivery_deadline', models.DateField(verbose_name='Son Teslim Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('cargo_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_posts', to='Profile.cargoowner', verbose_name='Yük Sahibi')),
                ('selected_transporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_posts', to='Profile.transporter', verbose_name='Seçilen Taşıyıcı')),
            ],
            options={
                'verbose_name': 'Yük İlanı',
                'verbose_name_plural': 'Yük İlanları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='cargo_cargo_created_0e9fb8_idx'), models.Index(fields=['status'], name='cargo_cargo_status_f173c8_idx'), models.Index(fields=['cargo_owner'], name='cargo_cargo_cargo_o_1bb890_idx')],
            },
        ),
    ]
