# Generated by Django 5.1.6 on 2025-03-04 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_alter_transporter_vehicle_type'),
        ('cargo', '0002_cargopost_package_count_alter_cargopost_cargo_type_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cargopost',
            name='cargo_cargo_created_0e9fb8_idx',
        ),
        migrations.RemoveIndex(
            model_name='cargopost',
            name='cargo_cargo_status_f173c8_idx',
        ),
        migrations.RemoveIndex(
            model_name='cargopost',
            name='cargo_cargo_cargo_o_1bb890_idx',
        ),
        migrations.RemoveField(
            model_name='cargopost',
            name='delivery_deadline',
        ),
        migrations.AddField(
            model_name='cargopost',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='İletişim E-posta'),
        ),
        migrations.AddField(
            model_name='cargopost',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='İletişim Telefonu'),
        ),
        migrations.AddField(
            model_name='cargopost',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Teslim Tarihi'),
        ),
        migrations.AddField(
            model_name='cargopost',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Geçerlilik Süresi'),
        ),
        migrations.AddField(
            model_name='cargopost',
            name='offer_count',
            field=models.PositiveIntegerField(default=0, help_text='Bu ilana yapılan teklif sayısı', verbose_name='Teklif Sayısı'),
        ),
        migrations.AddField(
            model_name='cargopost',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Görüntülenme Sayısı'),
        ),
        migrations.AlterField(
            model_name='cargopost',
            name='delivery_location',
            field=models.CharField(max_length=255, verbose_name='Teslim Yeri'),
        ),
        migrations.AlterField(
            model_name='cargopost',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='cargopost',
            name='package_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Paket Sayısı'),
        ),
        migrations.AlterField(
            model_name='cargopost',
            name='pickup_date',
            field=models.DateField(blank=True, null=True, verbose_name='Yükleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='cargopost',
            name='pickup_location',
            field=models.CharField(max_length=255, verbose_name='Yükleme Yeri'),
        ),
        migrations.AlterField(
            model_name='cargopost',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fiyat (TL)'),
        ),
        migrations.AlterField(
            model_name='cargopost',
            name='required_vehicle',
            field=models.CharField(blank=True, choices=[('truck', 'Kamyon'), ('semi_truck', 'Tır'), ('van', 'Kamyonet'), ('pickup', 'Pikap'), ('other', 'Diğer')], max_length=20, null=True, verbose_name='Gerekli Araç Tipi'),
        ),
        migrations.AlterField(
            model_name='cargopost',
            name='selected_transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_cargo_posts', to='Profile.transporter', verbose_name='Seçilen Taşıyıcı'),
        ),
        migrations.AlterField(
            model_name='cargopost',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('active', 'Aktif'), ('assigned', 'Taşıyıcıya Atandı'), ('in_progress', 'Taşıma Başladı'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi'), ('expired', 'Süresi Doldu')], default='pending', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='cargopost',
            name='title',
            field=models.CharField(max_length=255, verbose_name='İlan Başlığı'),
        ),
        migrations.AlterField(
            model_name='cargopost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='cargopost',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hacim (m³)'),
        ),
        migrations.AlterField(
            model_name='cargopost',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ağırlık (kg)'),
        ),
    ]
