# Generated by Django 5.1.6 on 2025-03-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_remove_cargopost_cargo_cargo_created_0e9fb8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargopost',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Teslimat Şehri'),
        ),
        migrations.AddField(
            model_name='cargopost',
            name='delivery_country',
            field=models.CharField(default='Türkiye', max_length=100, verbose_name='Teslimat Ülkesi'),
        ),
        migrations.AddField(
            model_name='cargopost',
            name='pickup_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Yükleme Şehri'),
        ),
        migrations.AddField(
            model_name='cargopost',
            name='pickup_country',
            field=models.CharField(default='Türkiye', max_length=100, verbose_name='Yükleme Ülkesi'),
        ),
    ]
