# Generated by Django 5.1.6 on 2025-04-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0004_cargopost_delivery_city_cargopost_delivery_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargopost',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='cargopost',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='cargopost',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='cargopost',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='cargopost',
            name='required_vehicle',
            field=models.CharField(blank=True, choices=[('open_truck', 'Açık Kasa Kamyon'), ('closed_truck', 'Kapalı Kasa Kamyon'), ('refrigerated_truck', 'Frigorifik Kamyon'), ('semi_trailer', 'Yarı Römork'), ('lowbed', 'Lowbed'), ('container_carrier', 'Konteyner Taşıyıcı'), ('tanker', 'Tanker'), ('tipper', 'Damperli Kamyon'), ('van', 'Panelvan'), ('pickup', 'Kamyonet'), ('other', 'Diğer')], max_length=20, null=True, verbose_name='Gerekli Araç Tipi'),
        ),
    ]
