# Generated by Django 5.1.6 on 2025-04-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0006_alter_cargopost_delivery_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargopost',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cargopost',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
